-- tabla de ejemplo : PACIENTES
CREATE TABLE PACIENTESMVC (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APELLIDO VARCHAR2(100),
    EDAD NUMBER,
    TELEFONO VARCHAR2(50),
    CORREO VARCHAR2(150)
);

COMMIT;