-- tabla de ejemplo : PACIENTES
CREATE TABLE PACIENTESMVC (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APELLIDO VARCHAR2(100),
    EDAD NUMBER,
    TELEFONO VARCHAR2(50),
    CORREO VARCHAR2(150)
);

COMMIT;

-- Inserts de ejemplo para la tabla PACIENTESMVC
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Ana', 'García', 28, '3001112233', 'ana.garcia@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Luis', 'Torres', 35, '3102223344', 'luis.torres@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Marta', 'Ríos', 42, '3113334455', 'marta.rios@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Carlos', 'Ramírez', 50, '3124445566', 'carlos.ramirez@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Elena', 'Morales', 30, '3135556677', 'elena.morales@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Jorge', 'Fernández', 27, '3146667788', 'jorge.fernandez@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Paola', 'Hernández', 31, '3157778899', 'paola.hernandez@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Diego', 'Castro', 40, '3168889900', 'diego.castro@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Valeria', 'Martínez', 22, '3179990011', 'valeria.martinez@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Santiago', 'Cano', 34, '3181112234', 'santiago.cano@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Laura', 'Vega', 29, '3192223345', 'laura.vega@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Andrés', 'Suárez', 38, '3003334456', 'andres.suarez@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Mariana', 'Ortiz', 26, '3014445567', 'mariana.ortiz@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Felipe', 'Jiménez', 41, '3025556678', 'felipe.jimenez@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Camila', 'Gómez', 33, '3036667789', 'camila.gomez@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Ricardo', 'Mendoza', 45, '3047778890', 'ricardo.mendoza@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Diana', 'Peña', 37, '3058889901', 'diana.pena@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Mateo', 'Cárdenas', 24, '3069990012', 'mateo.cardenas@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Isabela', 'Gutiérrez', 32, '3071112235', 'isabela.gutierrez@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Juan', 'Rojas', 36, '3082223346', 'juan.rojas@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Daniela', 'Salazar', 25, '3093334457', 'daniela.salazar@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Cristian', 'Navarro', 39, '3104445568', 'cristian.navarro@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Lucía', 'Peralta', 28, '3115556679', 'lucia.peralta@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Hernán', 'Reyes', 47, '3126667780', 'hernan.reyes@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Adriana', 'Beltrán', 29, '3137778891', 'adriana.beltran@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Oscar', 'Muñoz', 44, '3148889902', 'oscar.munoz@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Patricia', 'Aguilar', 30, '3159990013', 'patricia.aguilar@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Fernando', 'García', 52, '3161112236', 'fernando.garcia@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Natalia', 'Santos', 27, '3172223347', 'natalia.santos@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Iván', 'López', 31, '3183334458', 'ivan.lopez@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Claudia', 'Ramírez', 40, '3194445569', 'claudia.ramirez@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Sebastián', 'Cortés', 23, '3005556670', 'sebastian.cortes@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Juliana', 'Maldonado', 34, '3016667781', 'juliana.maldonado@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Álvaro', 'Paredes', 46, '3027778892', 'alvaro.paredes@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Gloria', 'Rivera', 38, '3038889903', 'gloria.rivera@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Mauricio', 'Silva', 42, '3049990014', 'mauricio.silva@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Sandra', 'Quintero', 33, '3051112237', 'sandra.quintero@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Rodrigo', 'Mejía', 49, '3062223348', 'rodrigo.mejia@example.com');
INSERT INTO PACIENTESMVC (NOMBRE, APELLIDO, EDAD, TELEFONO, CORREO) VALUES ('Beatriz', 'Valencia', 36, '3073334459', 'beatriz.valencia@example.com');

COMMIT;

SELECT * FROM PACIENTESMVC;